export const FIELD_DESCRIPTIONS: Record<string, string> = {
  month: "Abrechnungsmonat (1-12)",
  year: "Abrechnungsjahr",
  brutto_tax: "Steuerbruttolohn",
  brutto_av: "Bruttolohn zur Arbeitslosenversicherung",
  brutto_pv: "Bruttolohn zur Pflegeversicherung",
  brutto_rv: "Bruttolohn zur Rentenversicherung",
  brutto_kv: "Bruttolohn zur Krankenversicherung",
  deduction_tax_income: "Lohnsteuer",
  deduction_tax_church: "Kirchensteuer",
  deduction_tax_solidarity: "Solidaritätszuschlag",
  deduction_tax_other: "Sonstige steuerliche Abzüge",
  social_av: "Arbeitnehmeranteil Arbeitslosenversicherung",
  social_pv: "Arbeitnehmeranteil Pflegeversicherung",
  social_rv: "Arbeitnehmeranteil Rentenversicherung",
  social_kv: "Arbeitnehmeranteil Krankenversicherung",
  payout_netto: "Auszahlungsbetrag netto",
  payout_transfer: "Überweisung",
  payout_vwl: "Vermögenswirksame Leistungen",
  payout_other: "Sonstige Auszahlungen",
  incomes: "Liste der Einkommensbestandteile mit name, identifier und value",
};
