services:
  app:
    image: ghcr.io/lars-hubrich/gehaltskompass:lars-jan-work-branch
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
    environment:
      WATCHTOWER_LABEL_ENABLE: true

volumes:
  postgres-data:
